apiVersion: v1
kind: Service
metadata:
  name: vss-bridge
  namespace: vss-blueprint
  labels:
    app: vss-bridge
spec:
  type: ClusterIP
  selector:
    app: vss-bridge
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  sessionAffinity: None
